env:
  - DOCKER_COMPOSE_VERSION=1.4.2
  - VAULT_VERSION=1.3.0
  - VAULT_ADDR=127.0.0.1:8200
  - VAULT_TOKEN=root

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - curl -sLo vault.zip https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip
  - unzip vault.zip
  - sudo mv vault /usr/local/bin

script:
  - docker-compose build
  - docker-compose up -d
  - vault status
