version: '3'
services:
  vault:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VAULT_VERSION:1.3.0
    volumes:
      - ./entrypoint.sh:/bin/entrypoint.sh
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
    ports:
      - 8200:8200
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
      - VAULT_ADDRESS=http://0.0.0.0:8200
      - VAULT_HSM_PIN=1234
      - VAULT_HSM_KEY_LABEL=key
      - VAULT_HSM_HMAC_KEY_LABEL=hmac-key
      - VAULT_HSM_GENERATE_KEY=true
      - VAULT_HSM_LIB=/usr/lib/softhsm/libsofthsm2.so
    cap_add:
      - IPC_LOCK
    command: /bin/entrypoint.sh /usr/local/bin/vault server -config=/vault/config/vault.hcl